openapi: "3.0.3"
info:
  title: "rabbit_backend API"
  description: "rabbit_backend API"
  version: "1.0.0"
servers:
- url: "http://0.0.0.0:8080"
tags:
  - name: auth
    description: Auth API
paths:
  /auth/login:
    post:
      tags:
        - auth
      description: log in by user
      requestBody:
        description: A JSON object containing login password
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /auth/register:
    post:
      tags:
        - auth
      description: "Create user"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Success!"
components:
  schemas:
    User:
      type: "object"
      properties:
        email:
          type: string
          format: email
          example: login@gm.com
        password:
          type: string
          format: password
          example: password