version: '3.8'
services:
  db:
    container_name: rabbit_postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=rabbit
      - POSTGRES_PASSWORD=rabbit
      - POSTGRES_DB=rabbitDB
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    container_name: rabbit_app
    image: ghcr.io/grepfunlife/rabbit-backend:master
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DB_USER: rabbit
      DB_PASSWORD: rabbit
      DB_URL: jdbc:postgresql://rabbit_postgres:5432/rabbitDB
      JWT_SECRET: rabbit
      JWT_ISSUER: red.rabbit
      JWT_REALM: red.rabbit.hole
      DEV_MODE: true
    links:
      - db

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --interval 900
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db:
    driver: local